const jsonData = [
    {
      "clusterid": "aklan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "038",
      "clientid": null,
      "title": "Aklan Province",
      "email": null,
      "name": "aklan",
      "subtype": "province",
      "includeservices": "po.*|rptis.*|ticketing.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "aklan",
        "objid": "aklan",
        "title": "Aklan"
      },
      "channelid": "038",
      "isonline": "0"
    },
    {
      "clusterid": "aklan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "03801",
      "clientid": null,
      "title": "Kalibo",
      "email": null,
      "name": "kalibo",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "aklan",
        "objid": "aklan",
        "title": "Aklan"
      },
      "channelid": "03801",
      "isonline": "0"
    },
    {
      "clusterid": "aklan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "03802",
      "clientid": null,
      "title": "Altavas",
      "email": null,
      "name": "altavas",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "aklan",
        "objid": "aklan",
        "title": "Aklan"
      },
      "channelid": "03802",
      "isonline": "0"
    },
    {
      "clusterid": "aklan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "03807",
      "clientid": null,
      "title": "Ibajay",
      "email": null,
      "name": "ibajay",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "aklan",
        "objid": "aklan",
        "title": "Aklan"
      },
      "channelid": "03807",
      "isonline": "0"
    },
    {
      "clusterid": "aklan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "03812",
      "clientid": null,
      "title": "Malay",
      "email": null,
      "name": "malay",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "aklan",
        "objid": "aklan",
        "title": "Aklan"
      },
      "channelid": "03812",
      "isonline": "0"
    },
    {
      "clusterid": "aklan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "03813",
      "clientid": null,
      "title": "Malinao",
      "email": null,
      "name": "malinao",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "aklan",
        "objid": "aklan",
        "title": "Aklan"
      },
      "channelid": "03813",
      "isonline": "0"
    },
    {
      "clusterid": "aklanterminal",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "038CAG",
      "clientid": null,
      "title": "Cagban",
      "email": null,
      "name": "cagban",
      "subtype": "terminal",
      "includeservices": null,
      "excludeservices": ".*",
      "phoneno": null,
      "group": {
        "name": "aklanterminal",
        "objid": "aklanterminal",
        "title": "Aklan Terminals"
      },
      "channelid": "038CAG",
      "isonline": "0"
    },
    {
      "clusterid": "aklanterminal",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "038CAT",
      "clientid": null,
      "title": "Caticlan",
      "email": null,
      "name": "caticlan",
      "subtype": "terminal",
      "includeservices": null,
      "excludeservices": ".*",
      "phoneno": null,
      "group": {
        "name": "aklanterminal",
        "objid": "aklanterminal",
        "title": "Aklan Terminals"
      },
      "channelid": "038CAT",
      "isonline": "0"
    },
    {
      "clusterid": "albay",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "031",
      "clientid": null,
      "title": "Albay Province",
      "email": null,
      "name": "albay",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "albay",
        "objid": "albay",
        "title": "Albay"
      },
      "channelid": "031",
      "isonline": "0"
    },
    {
      "clusterid": "albay",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "137",
      "clientid": null,
      "title": "Legazpi City",
      "email": null,
      "name": "legazpi",
      "subtype": "city",
      "includeservices": ".*",
      "excludeservices": "ticketing.*|waterworks.*",
      "phoneno": null,
      "group": {
        "name": "albay",
        "objid": "albay",
        "title": "Albay"
      },
      "channelid": "137",
      "isonline": "0"
    },
    {
      "clusterid": "albay",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "207",
      "clientid": null,
      "title": "Ligao City",
      "email": null,
      "name": "ligao",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "albay",
        "objid": "albay",
        "title": "Albay"
      },
      "channelid": "207",
      "isonline": "0"
    },
    {
      "clusterid": "albay",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "208",
      "clientid": null,
      "title": "Tabaco City",
      "email": null,
      "name": "tabaco",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "albay",
        "objid": "albay",
        "title": "Albay"
      },
      "channelid": "208",
      "isonline": "0"
    },
    {
      "clusterid": "albay",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "03104",
      "clientid": null,
      "title": "Daraga",
      "email": null,
      "name": "daraga",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "albay",
        "objid": "albay",
        "title": "Albay"
      },
      "channelid": "03104",
      "isonline": "0"
    },
    {
      "clusterid": "antique",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04001",
      "clientid": null,
      "title": "San Jose de Buenavista",
      "email": null,
      "name": "sjdb",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "antique",
        "objid": "antique",
        "title": "Antique"
      },
      "channelid": "04001",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "047",
      "clientid": null,
      "title": "Bohol Province",
      "email": null,
      "name": "bohol",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "047",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "154",
      "clientid": null,
      "title": "Tagbilaran City",
      "email": null,
      "name": "tagbilaran",
      "subtype": "city",
      "includeservices": ".*",
      "excludeservices": "ticketing.*",
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "154",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04701",
      "clientid": null,
      "title": "Alburquerque",
      "email": null,
      "name": "alburquerque",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04701",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04711",
      "clientid": null,
      "title": "Candijay",
      "email": null,
      "name": "candijay",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04711",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04713",
      "clientid": null,
      "title": "Catigbian",
      "email": null,
      "name": "catigbian",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04713",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04722",
      "clientid": null,
      "title": "Garcia Hernandez",
      "email": null,
      "name": "garciahernandez",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04722",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04732",
      "clientid": null,
      "title": "Carlos P. Garcia",
      "email": null,
      "name": "carlospgarcia",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04732",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04733",
      "clientid": null,
      "title": "Panglao",
      "email": null,
      "name": "panglao",
      "subtype": "municipality",
      "includeservices": ".*",
      "excludeservices": "ticketing.*",
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04733",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04738",
      "clientid": null,
      "title": "San Miguel",
      "email": null,
      "name": "sanmiguel",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04738",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04742",
      "clientid": null,
      "title": "Talibon",
      "email": null,
      "name": "talibon",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04742",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04743",
      "clientid": null,
      "title": "Trinidad",
      "email": null,
      "name": "trinidad",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04743",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04744",
      "clientid": null,
      "title": "Tubigon",
      "email": null,
      "name": "tubigon",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04744",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04745",
      "clientid": null,
      "title": "Ubay",
      "email": null,
      "name": "ubay",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04745",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04746",
      "clientid": null,
      "title": "Valencia",
      "email": null,
      "name": "valencia",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04746",
      "isonline": "0"
    },
    {
      "clusterid": "bohol",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04747",
      "clientid": null,
      "title": "Bien Unido",
      "email": null,
      "name": "bienunido",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bohol",
        "objid": "bohol",
        "title": "Bohol"
      },
      "channelid": "04747",
      "isonline": "0"
    },
    {
      "clusterid": "bukidnon",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "059",
      "clientid": null,
      "title": "Bukidnon Province",
      "email": null,
      "name": "bukidnon",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bukidnon",
        "objid": "bukidnon",
        "title": "Bukidnon"
      },
      "channelid": "059",
      "isonline": "0"
    },
    {
      "clusterid": "bukidnon",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05914",
      "clientid": null,
      "title": "Malitbog",
      "email": null,
      "name": "malitbog",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bukidnon",
        "objid": "bukidnon",
        "title": "Bukidnon"
      },
      "channelid": "05914",
      "isonline": "0"
    },
    {
      "clusterid": "bukidnon",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05916",
      "clientid": null,
      "title": "Maramag",
      "email": null,
      "name": "maramag",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bukidnon",
        "objid": "bukidnon",
        "title": "Bukidnon"
      },
      "channelid": "05916",
      "isonline": "0"
    },
    {
      "clusterid": "bukidnon",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05920",
      "clientid": null,
      "title": "Sumilao",
      "email": null,
      "name": "sumilao",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "bukidnon",
        "objid": "bukidnon",
        "title": "Bukidnon"
      },
      "channelid": "05920",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "135",
      "clientid": null,
      "title": "Naga City",
      "email": null,
      "name": "naga",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "135",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "136",
      "clientid": null,
      "title": "Iriga City",
      "email": null,
      "name": "iriga",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "136",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02602",
      "clientid": null,
      "title": "Baao",
      "email": null,
      "name": "baao",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "02602",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02609",
      "clientid": null,
      "title": "Calabanga",
      "email": null,
      "name": "calabanga",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "02609",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02618",
      "clientid": null,
      "title": "Libmanan",
      "email": null,
      "name": "libmanan",
      "subtype": "municipality",
      "includeservices": ".*",
      "excludeservices": "ticketing.*|waterworks.*",
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "02618",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02620",
      "clientid": null,
      "title": "Magarao",
      "email": null,
      "name": "magarao",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "02620",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02630",
      "clientid": null,
      "title": "San Fernando",
      "email": null,
      "name": "sanfernando",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "02630",
      "isonline": "0"
    },
    {
      "clusterid": "camsur",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02632",
      "clientid": null,
      "title": "Sipocot",
      "email": null,
      "name": "sipocot",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "camsur",
        "objid": "camsur",
        "title": "Camarines Sur"
      },
      "channelid": "02632",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "027",
      "clientid": null,
      "title": "Catanduanes Province",
      "email": null,
      "name": "catanduanes",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "027",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02701",
      "clientid": null,
      "title": "Bagamanoc",
      "email": null,
      "name": "bagamanoc",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02701",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02702",
      "clientid": null,
      "title": "Baras",
      "email": null,
      "name": "baras",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02702",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02703",
      "clientid": null,
      "title": "Bato",
      "email": null,
      "name": "bato",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02703",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02704",
      "clientid": null,
      "title": "Caramoran",
      "email": null,
      "name": "caramoran",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02704",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02705",
      "clientid": null,
      "title": "Gigmoto",
      "email": null,
      "name": "gigmoto",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02705",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02706",
      "clientid": null,
      "title": "Pandan",
      "email": null,
      "name": "pandan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02706",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02707",
      "clientid": null,
      "title": "Panganiban",
      "email": null,
      "name": "panganiban",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02707",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02708",
      "clientid": null,
      "title": "San Andres",
      "email": null,
      "name": "sanandres",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02708",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02709",
      "clientid": null,
      "title": "San Miguel",
      "email": null,
      "name": "sanmiguel",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02709",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02710",
      "clientid": null,
      "title": "Viga",
      "email": null,
      "name": "viga",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02710",
      "isonline": "0"
    },
    {
      "clusterid": "catanduanes",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "02711",
      "clientid": null,
      "title": "Virac",
      "email": null,
      "name": "virac",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "catanduanes",
        "objid": "catanduanes",
        "title": "Catanduanes"
      },
      "channelid": "02711",
      "isonline": "0"
    },
    {
      "clusterid": "cebu",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04301",
      "clientid": null,
      "title": "Danao City",
      "email": null,
      "name": "danao",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "cebu",
        "objid": "cebu",
        "title": "Cebu"
      },
      "channelid": "04301",
      "isonline": "0"
    },
    {
      "clusterid": "cebu",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "04321",
      "clientid": null,
      "title": "Dalaguete",
      "email": null,
      "name": "dalaguete",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "cebu",
        "objid": "cebu",
        "title": "Cebu"
      },
      "channelid": "04321",
      "isonline": "0"
    },
    {
      "clusterid": "davor",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "064",
      "clientid": null,
      "title": "Davao Oriental Province",
      "email": null,
      "name": "davor",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "davaooriental",
        "objid": "davor",
        "title": "Davao Oriental"
      },
      "channelid": "064",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "063",
      "clientid": null,
      "title": "Davao del Norte Province",
      "email": null,
      "name": "davaodelnorte",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "063",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "179",
      "clientid": null,
      "title": "Samal City",
      "email": null,
      "name": "igacos",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "179",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "195",
      "clientid": null,
      "title": "Panabo City",
      "email": null,
      "name": "panabo",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "195",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06301",
      "clientid": null,
      "title": "Asuncion",
      "email": null,
      "name": "asuncion",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06301",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06302",
      "clientid": null,
      "title": "Braulio E. Dujali",
      "email": null,
      "name": "dujali",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06302",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06303",
      "clientid": null,
      "title": "Carmen",
      "email": null,
      "name": "carmen",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06303",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06304",
      "clientid": null,
      "title": "Kapalong",
      "email": null,
      "name": "kapalong",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06304",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06305",
      "clientid": null,
      "title": "New Corella",
      "email": null,
      "name": "newcorella",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06305",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06306",
      "clientid": null,
      "title": "San Isidro",
      "email": null,
      "name": "sanisidro",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06306",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06307",
      "clientid": null,
      "title": "Sto. Tomas",
      "email": null,
      "name": "stotomas",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06307",
      "isonline": "0"
    },
    {
      "clusterid": "ddn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06308",
      "clientid": null,
      "title": "Talaingod",
      "email": null,
      "name": "talaingod",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddn",
        "objid": "ddn",
        "title": "Davao del Norte"
      },
      "channelid": "06308",
      "isonline": "0"
    },
    {
      "clusterid": "ddo",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "079",
      "clientid": null,
      "title": "Davao de Oro",
      "email": null,
      "name": "ddo",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddo",
        "objid": "ddo",
        "title": "Davao de Oro"
      },
      "channelid": "079",
      "isonline": "0"
    },
    {
      "clusterid": "ddo",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07901",
      "clientid": null,
      "title": "Compostela",
      "email": null,
      "name": "compostela",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddo",
        "objid": "ddo",
        "title": "Davao de Oro"
      },
      "channelid": "07901",
      "isonline": "0"
    },
    {
      "clusterid": "ddo",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07903",
      "clientid": null,
      "title": "Mabini",
      "email": null,
      "name": "mabini",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddo",
        "objid": "ddo",
        "title": "Davao de Oro"
      },
      "channelid": "07903",
      "isonline": "0"
    },
    {
      "clusterid": "ddo",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07904",
      "clientid": null,
      "title": "Maco",
      "email": null,
      "name": "maco",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddo",
        "objid": "ddo",
        "title": "Davao de Oro"
      },
      "channelid": "07904",
      "isonline": "0"
    },
    {
      "clusterid": "ddo",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07907",
      "clientid": null,
      "title": "Monkayo",
      "email": null,
      "name": "monkayo",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddo",
        "objid": "ddo",
        "title": "Davao de Oro"
      },
      "channelid": "07907",
      "isonline": "0"
    },
    {
      "clusterid": "ddo",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07909",
      "clientid": null,
      "title": "Nabunturan",
      "email": null,
      "name": "nabunturan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddo",
        "objid": "ddo",
        "title": "Davao de Oro"
      },
      "channelid": "07909",
      "isonline": "0"
    },
    {
      "clusterid": "ddo",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07911",
      "clientid": null,
      "title": "Pantukan",
      "email": null,
      "name": "pantukan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ddo",
        "objid": "ddo",
        "title": "Davao de Oro"
      },
      "channelid": "07911",
      "isonline": "0"
    },
    {
      "clusterid": "gensan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "173",
      "clientid": null,
      "title": "General Santos City",
      "email": null,
      "name": "gensan",
      "subtype": "city",
      "includeservices": ".*",
      "excludeservices": "ticketing.*|waterworks.*",
      "phoneno": null,
      "group": {
        "name": "gensan",
        "objid": "gensan",
        "title": "General Santos"
      },
      "channelid": "173",
      "isonline": "0"
    },
    {
      "clusterid": "guimaras",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "075",
      "clientid": null,
      "title": "Guimaras Province",
      "email": null,
      "name": "guimaras",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "guimaras",
        "objid": "guimaras",
        "title": "Guimaras "
      },
      "channelid": "075",
      "isonline": "0"
    },
    {
      "clusterid": "guimaras",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07501",
      "clientid": null,
      "title": "Buenavista",
      "email": null,
      "name": "buenavista",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "guimaras",
        "objid": "guimaras",
        "title": "Guimaras "
      },
      "channelid": "07501",
      "isonline": "0"
    },
    {
      "clusterid": "guimaras",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07502",
      "clientid": null,
      "title": "Jordan",
      "email": null,
      "name": "jordan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "guimaras",
        "objid": "guimaras",
        "title": "Guimaras "
      },
      "channelid": "07502",
      "isonline": "0"
    },
    {
      "clusterid": "guimaras",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07503",
      "clientid": null,
      "title": "Nueva Valencia",
      "email": null,
      "name": "nuevavalencia",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "guimaras",
        "objid": "guimaras",
        "title": "Guimaras "
      },
      "channelid": "07503",
      "isonline": "0"
    },
    {
      "clusterid": "guimaras",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07504",
      "clientid": null,
      "title": "San Lorenzo",
      "email": null,
      "name": "sanlorenzo",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "guimaras",
        "objid": "guimaras",
        "title": "Guimaras "
      },
      "channelid": "07504",
      "isonline": "0"
    },
    {
      "clusterid": "guimaras",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07505",
      "clientid": null,
      "title": "Sibunag",
      "email": null,
      "name": "sibunag",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "guimaras",
        "objid": "guimaras",
        "title": "Guimaras "
      },
      "channelid": "07505",
      "isonline": "0"
    },
    {
      "clusterid": "ilocosnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "003",
      "clientid": null,
      "title": "Ilocos Norte",
      "email": null,
      "name": "ilocosnorte",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ilocosnorte",
        "objid": "ilocosnorte",
        "title": "Ilocos Norte"
      },
      "channelid": "003",
      "isonline": "0"
    },
    {
      "clusterid": "ilocosnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "00312",
      "clientid": null,
      "title": "Marcos",
      "email": null,
      "name": "marcos",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ilocosnorte",
        "objid": "ilocosnorte",
        "title": "Ilocos Norte"
      },
      "channelid": "00312",
      "isonline": "0"
    },
    {
      "clusterid": "ilocosnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "00314",
      "clientid": null,
      "title": "Pagudpud",
      "email": null,
      "name": "pagudpud",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ilocosnorte",
        "objid": "ilocosnorte",
        "title": "Ilocos Norte"
      },
      "channelid": "00314",
      "isonline": "0"
    },
    {
      "clusterid": "ilocosnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "00317",
      "clientid": null,
      "title": "Piddig",
      "email": null,
      "name": "piddig",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ilocosnorte",
        "objid": "ilocosnorte",
        "title": "Ilocos Norte"
      },
      "channelid": "00317",
      "isonline": "0"
    },
    {
      "clusterid": "ilocosnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "00319",
      "clientid": null,
      "title": "San Nicolas",
      "email": null,
      "name": "sannicolas",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ilocosnorte",
        "objid": "ilocosnorte",
        "title": "Ilocos Norte"
      },
      "channelid": "00319",
      "isonline": "0"
    },
    {
      "clusterid": "ilocosnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "00320",
      "clientid": null,
      "title": "Sarrat",
      "email": null,
      "name": "sarrat",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ilocosnorte",
        "objid": "ilocosnorte",
        "title": "Ilocos Norte"
      },
      "channelid": "00320",
      "isonline": "0"
    },
    {
      "clusterid": "ilocosnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "00321",
      "clientid": null,
      "title": "Solsona",
      "email": null,
      "name": "solsona",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "ilocosnorte",
        "objid": "ilocosnorte",
        "title": "Ilocos Norte"
      },
      "channelid": "00321",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "057",
      "clientid": null,
      "title": "Lanao del Norte Province",
      "email": null,
      "name": "lanaonorte",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "057",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "169",
      "clientid": null,
      "title": "Iligan City",
      "email": null,
      "name": "iligan",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "169",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05701",
      "clientid": null,
      "title": "Bacolod",
      "email": null,
      "name": "bacolod",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05701",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05703",
      "clientid": null,
      "title": "Baroy",
      "email": null,
      "name": "baroy",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05703",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05704",
      "clientid": null,
      "title": "Kapatagan",
      "email": null,
      "name": "kapatagan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05704",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05707",
      "clientid": null,
      "title": "Kolambugan",
      "email": null,
      "name": "kolambugan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05707",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05708",
      "clientid": null,
      "title": "Lala",
      "email": null,
      "name": "lala",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05708",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05709",
      "clientid": null,
      "title": "Linamon",
      "email": null,
      "name": "linamon",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05709",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05711",
      "clientid": null,
      "title": "Maigo",
      "email": null,
      "name": "maigo",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05711",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05717",
      "clientid": null,
      "title": "Salvador",
      "email": null,
      "name": "salvador",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05717",
      "isonline": "0"
    },
    {
      "clusterid": "lanaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05722",
      "clientid": null,
      "title": "Tubod",
      "email": null,
      "name": "tubod",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "lanaodelnorte",
        "objid": "lanaodelnorte",
        "title": "Lanao del Norte"
      },
      "channelid": "05722",
      "isonline": "0"
    },
    {
      "clusterid": "masbate",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "209",
      "clientid": null,
      "title": "Masbate City",
      "email": null,
      "name": "masbate",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "masbate",
        "objid": "masbate",
        "title": "Masbate"
      },
      "channelid": "209",
      "isonline": "0"
    },
    {
      "clusterid": "misoc",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "051",
      "clientid": null,
      "title": "Misamis Occidental",
      "email": null,
      "name": "misocc",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "misoc",
        "objid": "misoc",
        "title": "Misamis Occidental"
      },
      "channelid": "051",
      "isonline": "0"
    },
    {
      "clusterid": "misoc",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "166",
      "clientid": null,
      "title": "Oroquieta City",
      "email": null,
      "name": "oroquieta",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "misoc",
        "objid": "misoc",
        "title": "Misamis Occidental"
      },
      "channelid": "166",
      "isonline": "0"
    },
    {
      "clusterid": "misoc",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05102",
      "clientid": null,
      "title": "Baliangao",
      "email": null,
      "name": "baliangao",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "misoc",
        "objid": "misoc",
        "title": "Misamis Occidental"
      },
      "channelid": "05102",
      "isonline": "0"
    },
    {
      "clusterid": "misoc",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05105",
      "clientid": null,
      "title": "Clarin",
      "email": null,
      "name": "clarin",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "misoc",
        "objid": "misoc",
        "title": "Misamis Occidental"
      },
      "channelid": "05105",
      "isonline": "0"
    },
    {
      "clusterid": "misor",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "05212",
      "clientid": null,
      "title": "Claveria",
      "email": null,
      "name": "claveria",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "misor",
        "objid": "misor",
        "title": "Misamis Oriental"
      },
      "channelid": "05212",
      "isonline": "0"
    },
    {
      "clusterid": "negocc",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "140",
      "clientid": null,
      "title": "Cadiz City",
      "email": null,
      "name": "cadiz",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "negoc",
        "objid": "negocc",
        "title": "Negros Occidental"
      },
      "channelid": "140",
      "isonline": "0"
    },
    {
      "clusterid": "negocc",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "142",
      "clientid": null,
      "title": "San Carlos City",
      "email": null,
      "name": "sancarlos",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "negoc",
        "objid": "negocc",
        "title": "Negros Occidental"
      },
      "channelid": "142",
      "isonline": "0"
    },
    {
      "clusterid": "negor",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "046",
      "clientid": null,
      "title": "Tanjay City",
      "email": null,
      "name": "tanjay",
      "subtype": "city",
      "includeservices": ".*",
      "excludeservices": "ticketing.*|waterworks.*",
      "phoneno": null,
      "group": {
        "name": "negor",
        "objid": "negor",
        "title": "Negros Oriental"
      },
      "channelid": "046",
      "isonline": "0"
    },
    {
      "clusterid": "negor",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "218",
      "clientid": null,
      "title": "Bayawan City",
      "email": null,
      "name": "bayawan",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "negor",
        "objid": "negor",
        "title": "Negros Oriental"
      },
      "channelid": "218",
      "isonline": "0"
    },
    {
      "clusterid": "nuevaecija",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "191",
      "clientid": null,
      "title": "Gapan City",
      "email": null,
      "name": "gapan",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "nuevaecija",
        "objid": "nuevaecija",
        "title": "Nueva Ecija"
      },
      "channelid": "191",
      "isonline": "0"
    },
    {
      "clusterid": "nuevavizcaya",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "01205",
      "clientid": null,
      "title": "Bayombong",
      "email": null,
      "name": "bayombong",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "nuevavizcaya",
        "objid": "nuevavizcaya",
        "title": "Nueva Vizcaya"
      },
      "channelid": "01205",
      "isonline": "0"
    },
    {
      "clusterid": "nuevavizcaya",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "01214",
      "clientid": null,
      "title": "Solano",
      "email": null,
      "name": "solano",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "nuevavizcaya",
        "objid": "nuevavizcaya",
        "title": "Nueva Vizcaya"
      },
      "channelid": "01214",
      "isonline": "0"
    },
    {
      "clusterid": "palawan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "066",
      "clientid": null,
      "title": "Palawan Province",
      "email": null,
      "name": "palawan",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "palawan",
        "objid": "palawan",
        "title": "Palawan"
      },
      "channelid": "066",
      "isonline": "0"
    },
    {
      "clusterid": "palawan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "134",
      "clientid": null,
      "title": "Puerto Princesa City",
      "email": null,
      "name": "puertoprincesa",
      "subtype": "city",
      "includeservices": ".*",
      "excludeservices": "ticketing.*|waterworks.*",
      "phoneno": null,
      "group": {
        "name": "palawan",
        "objid": "palawan",
        "title": "Palawan"
      },
      "channelid": "134",
      "isonline": "0"
    },
    {
      "clusterid": "palawan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06601",
      "clientid": null,
      "title": "Aborlan",
      "email": null,
      "name": "aborlan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "palawan",
        "objid": "palawan",
        "title": "Palawan"
      },
      "channelid": "06601",
      "isonline": "0"
    },
    {
      "clusterid": "palawan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06621",
      "clientid": null,
      "title": "San Vicente",
      "email": null,
      "name": "sanvicente",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "palawan",
        "objid": "palawan",
        "title": "Palawan"
      },
      "channelid": "06621",
      "isonline": "0"
    },
    {
      "clusterid": "palawan",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "06623",
      "clientid": null,
      "title": "Taytay",
      "email": null,
      "name": "taytay",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "palawan",
        "objid": "palawan",
        "title": "Palawan"
      },
      "channelid": "06623",
      "isonline": "0"
    },
    {
      "clusterid": "quezon",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "236",
      "clientid": null,
      "title": "Tayabas City",
      "email": null,
      "name": "tayabas",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "quezon",
        "objid": "quezon",
        "title": "Quezon"
      },
      "channelid": "236",
      "isonline": "0"
    },
    {
      "clusterid": "quezon",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "01536",
      "clientid": null,
      "title": "Sariaya",
      "email": null,
      "name": "sariaya",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "quezon",
        "objid": "quezon",
        "title": "Quezon"
      },
      "channelid": "01536",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "076",
      "clientid": null,
      "title": "Sarangani Province",
      "email": null,
      "name": "sarangani",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "076",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07601",
      "clientid": null,
      "title": "Alabel",
      "email": null,
      "name": "alabel",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "07601",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07602",
      "clientid": null,
      "title": "Glan",
      "email": null,
      "name": "glan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "07602",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07603",
      "clientid": null,
      "title": "Kiamba",
      "email": null,
      "name": "kiamba",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "07603",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07604",
      "clientid": null,
      "title": "Maasim",
      "email": null,
      "name": "maasim",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "07604",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07605",
      "clientid": null,
      "title": "Maitum",
      "email": null,
      "name": "maitum",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "07605",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07606",
      "clientid": null,
      "title": "Malapatan",
      "email": null,
      "name": "malapatan",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "07606",
      "isonline": "0"
    },
    {
      "clusterid": "sarangani",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "07607",
      "clientid": null,
      "title": "Malungon",
      "email": null,
      "name": "malungon",
      "subtype": "municipality",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "sarangani",
        "objid": "sarangani",
        "title": "Sarangani"
      },
      "channelid": "07607",
      "isonline": "0"
    },
    {
      "clusterid": "sorsogon",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "189",
      "clientid": null,
      "title": "Sorsogon City",
      "email": null,
      "name": "sorsogoncity",
      "subtype": "city",
      "includeservices": ".*",
      "excludeservices": "ticketing.*|waterworks.*",
      "phoneno": null,
      "group": {
        "name": "sorsogon",
        "objid": "sorsogon",
        "title": "Sorsogon"
      },
      "channelid": "189",
      "isonline": "0"
    },
    {
      "clusterid": "surigaodelnorte",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "043",
      "clientid": null,
      "title": "Surigao del Norte Province",
      "email": null,
      "name": "surigaonorte",
      "subtype": "province",
      "includeservices": "po.*|rptis.*",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "surigaodelnorte",
        "objid": "surigaodelnorte",
        "title": "Surigao Del Norte"
      },
      "channelid": "043",
      "isonline": "0"
    },
    {
      "clusterid": "zamboanga",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "160",
      "clientid": null,
      "title": "Zamboanga City",
      "email": null,
      "name": "zamboanga",
      "subtype": "city",
      "includeservices": "po.*|rptis.*|bpls.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "zamboanga",
        "objid": "zamboanga",
        "title": "Zamboanga"
      },
      "channelid": "160",
      "isonline": "0"
    },
    {
      "clusterid": "zdn",
      "state": "ACTIVE",
      "type": "lgu",
      "id": "158",
      "clientid": null,
      "title": "Dapitan City",
      "email": null,
      "name": "dapitan",
      "subtype": "city",
      "includeservices": "bpls.*|rptis.*|po.*|renewbusiness",
      "excludeservices": null,
      "phoneno": null,
      "group": {
        "name": "zdn",
        "objid": "zdn",
        "title": "Zamboanga Del Norte"
      },
      "channelid": "158",
      "isonline": "0"
    }
  ];

const getData = (req: any, res: any) => {
  res.status(200).json(jsonData);
};

export default getData;